# Generated by Django 2.1 on 2019-01-30 23:34

from django.db import migrations


def create_test_pizzas(apps, schema_editor):
    Pizza = apps.get_model('pizzas', 'Pizza')

    Pizza.objects.bulk_create([
        Pizza(name='Pepperoni', description='Just pepperoni'),
        Pizza(name='Meat Lovers', description='Just meat'),
        Pizza(name='Hawaiian', description='Just pineapple')
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_pizzas),
    ]
