# Generated by Django 2.1 on 2019-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Phone for driver to contact', max_length=16, unique=True, verbose_name='Phone')),
                ('address', models.TextField(help_text='Address for pizza delivery', verbose_name='Address')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
