# Generated by Django 2.1 on 2019-01-30 23:30

from django.db import migrations


def create_test_customers(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')

    data = {
        'first_name': 'John',
        'last_name': 'Doe',
        'email': 'john.doe@mail.com',
        'phone': '+50400875432',
        'address': 'I live in narnia, ask for John Doe to whomever'
    }

    Customer.objects.create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_customers),
    ]
