# Generated by Django 2.1 on 2019-01-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, unique=True, verbose_name='Order #')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Received'), (2, 'In Process'), (3, 'Out For Delivery'), (4, 'Delivered'), (5, 'Returned')], default=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large')], verbose_name='Size')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('customer_details', models.TextField(blank=True, verbose_name='Details')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Order #')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzas.Pizza', verbose_name='Pizza')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'pizza', 'size')},
        ),
    ]
