# Generated by Django 2.1 on 2019-01-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190129_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.Order', verbose_name='Order #'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pizzas.Pizza', verbose_name='Pizza'),
            preserve_default=False,
        ),
    ]
